---
name: Test peers.yaml

on:
  push:
  schedule:
    # Saturday 04:30 UTC
    - cron: "30 4 * * 6"
  workflow_dispatch:

jobs:
  test-peers-yaml:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipaddr requests pyyaml
        pip install --user yamllint

    - name: Test peers.yaml (YAML syntax)
      # Allow for longer line lengths
      run: |
        yamllint -d "{ extends: default, rules: { line-length: { max: 120 } } }" peers.yaml

    - name: Test peers.yaml validity
      run: python ./tests/test_peering_relations.py
